# Generated by Django 5.0.4 on 2024-05-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='urls',
            field=models.ManyToManyField(related_name='url_models', to='tasks.url'),
        ),
    ]
