# Generated by Django 5.0.4 on 2024-05-25 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_project_taskcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskURL',
        ),
    ]
