# Generated by Django 5.0.4 on 2024-04-29 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_membership_role'),
        ('user', '0005_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.company'),
        ),
    ]
