# Generated by Django 5.0.4 on 2024-04-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country_code',
            field=models.CharField(choices=[('+91', 'IN'), ('+1', 'USA'), ('+2', 'CAN')], default='+91', max_length=10),
        ),
    ]
