# Generated by Django 5.0.4 on 2024-04-20 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_country_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.PositiveSmallIntegerField(choices=[(1, 'Owner'), (2, 'President'), (3, 'Vice President'), (4, 'Project Admin'), (5, 'Project Manager'), (6, 'Engineer'), (7, 'Inspector'), (8, 'IT Person'), (9, 'Quality Control Manager'), (10, 'Construction Admin'), (11, 'Architect'), (12, 'Other')], default=1)),
                ('company', models.CharField(max_length=100)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'General Construction'), (2, 'Specialty Construction'), (3, 'Owner / Developer'), (4, 'Architect / Designer'), (5, 'Other')], default=3)),
                ('industry', models.PositiveSmallIntegerField(choices=[(1, 'Commercial'), (2, 'Education'), (3, 'Healthcare'), (4, 'Government'), (5, 'Civil'), (6, 'Residential'), (7, 'Other')], default=7)),
                ('country_code', models.CharField(choices=[('+91', 'IN'), ('+1', 'USA'), ('+2', 'CAN')], default='+91', max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
