# Generated by Django 5.0.4 on 2024-04-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
